<a href="https://colab.research.google.com/github/zakari90/machine-learning/blob/main/car_drive_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd

cars = pd.read_csv("/content/drive/MyDrive/hsoub ai/machine learning/regression/fuel.csv")
cars.head()

,id,make,model,year,VClass,drive,trans,fuelType,cylinders,displ,pv2,pv4,city,UCity,highway,UHighway,comb,co2,feScore,ghgScore
0,32204,Nissan,GT-R,2013,Subcompact Cars,All-Wheel Drive,Automatic (AM6),Premium Gasoline,6,3.8,79,0,16.4596,20.2988,22.5568,30.1798,18.7389,471,4,4
1,32205,Volkswagen,CC,2013,Compact Cars,Front-Wheel Drive,Automatic (AM-S6),Premium Gasoline,4,2.0,94,0,21.8706,26.9770,31.0367,42.4936,25.2227,349,6,6
2,32206,Volkswagen,CC,2013,Compact Cars,Front-Wheel Drive,Automatic (S6),Premium Gasoline,6,3.6,94,0,17.4935,21.2000,26.5716,35.1000,20.6716,429,5,5
3,32207,Volkswagen,CC 4motion,2013,Compact Cars,All-Wheel Drive,Automatic (S6),Premium Gasoline,6,3.6,94,0,16.9415,20.5000,25.2190,33.5000,19.8774,446,5,5
4,32208,Chevrolet,Malibu eAssist,2013,Midsize Cars,Front-Wheel Drive,Automatic (S6),Regular Gasoline,4,2.4,0,95,24.7726,31.9796,35.5340,51.8816,28.6813,310,8,8

In [17]:
# from sklearn.preprocessing import LabelEncoder
# laberEconder_gender = LabelEncoder()
# cars.iloc[:,5]= laberEconder_gender.fit_transform(cars.iloc[:,5])
# cars.iloc[:,5]
cars['class_label'] = cars["drive"].apply(lambda x: 1 if x == 'Front-Wheel Drive' else 0)
cars['class_label']

0       0
1       1
2       1
3       0
4       1
       ..
3924    1
3925    1
3926    1
3927    0
3928    0
Name: class_label, Length: 3929, dtype: int64

In [18]:
cars_new = cars[["make", "model", "VClass", "drive", "displ", "comb", "class_label"]]

cars_new.head(5)

,make,model,VClass,drive,displ,comb,class_label
0,Nissan,GT-R,Subcompact Cars,All-Wheel Drive,3.8,18.7389,0
1,Volkswagen,CC,Compact Cars,Front-Wheel Drive,2.0,25.2227,1
2,Volkswagen,CC,Compact Cars,Front-Wheel Drive,3.6,20.6716,1
3,Volkswagen,CC 4motion,Compact Cars,All-Wheel Drive,3.6,19.8774,0
4,Chevrolet,Malibu eAssist,Midsize Cars,Front-Wheel Drive,2.4,28.6813,1

In [19]:
from sklearn.model_selection import train_test_split

X = cars_new[['displ', 'comb']]
y = cars["class_label"]

# data splitting
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [20]:
from sklearn.preprocessing import StandardScaler

stscaler = StandardScaler()

X = cars_new[['displ', 'comb']]

X_scaled = stscaler.fit_transform(X)

X_train_scaled, X_test_scaled, _, _ = train_test_split(X_scaled, y, random_state=0)

In [21]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression().fit(X_train.values, y_train)

model_scaled = LogisticRegression().fit(X_train_scaled, y_train)

In [22]:
y_pred = model.predict(X_test.values)

In [23]:
from sklearn import metrics

cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)

accuracy = metrics.accuracy_score(y_test, y_pred)
print("Accuracy score:", accuracy)

precision = metrics.precision_score(y_test, y_pred)
print("Precision score:", precision)

recall = metrics.recall_score(y_test, y_pred)
print("Recall score:", recall)

[[510  90]
 [ 87 296]]
Accuracy score: 0.8199389623601221
Precision score: 0.7668393782383419
Recall score: 0.7728459530026109

In [24]:
y_pred_scaled = model_scaled.predict(X_test_scaled)

In [25]:
cm = metrics.confusion_matrix(y_test, y_pred_scaled)
print(cm)

accuracy = metrics.accuracy_score(y_test, y_pred_scaled)
print("Accuracy score:", accuracy)

precision = metrics.precision_score(y_test, y_pred_scaled)
print("Precision score:", precision)

recall = metrics.recall_score(y_test, y_pred_scaled)
print("Recall score:", recall)

[[508  92]
 [ 87 296]]
Accuracy score: 0.8179043743641913
Precision score: 0.7628865979381443
Recall score: 0.7728459530026109

In [26]:
car = model.predict([[4.4, 16.1]])

if car == 1:
    print("The Car is Front-Wheel Driven")
else:
    print("The Car is Back-Wheel Driven or All-Wheel Driven")

The Car is Back-Wheel Driven or All-Wheel Driven

In [27]:
car_1 = model.predict([[2.526, 30.7]])

if car_1 == 1:
    print("The Car is Front-Wheel Driven")
else:
    print("The Car is Back-Wheel Driven or All-Wheel Driven")

The Car is Front-Wheel Driven