<a href="https://colab.research.google.com/github/zakari90/machine-learning/blob/main/Cross_validation_Iphone_purchase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

file_path = "/content/drive/MyDrive/hsoub ai/machine learning/regression/iPhone.csv"
dataset = pd.read_csv(file_path)

print(dataset.head())

   Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0
4    Male   19   76000                0

In [2]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, 3]

In [3]:
from sklearn.preprocessing import LabelEncoder
labelEncoder_gender =  LabelEncoder()

X[:,0] = labelEncoder_gender.fit_transform(X[:,0])

In [4]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)

In [5]:
from sklearn.model_selection import cross_val_score

def cv_comparison_classification(models, X, y, cv):

    cv_df = pd.DataFrame()

    for model in models:

        acc = cross_val_score(model, X, y, scoring='accuracy', cv=cv)

        acc_avg = round(acc.mean(), 3)

        cv_df[str(model)] = [ acc_avg]
        cv_df.index = ['Accuracy']

    return cv_df

In [6]:
dataset.describe()

              Age         Salary  Purchase Iphone
count  400.000000     400.000000       400.000000
mean    37.655000   69742.500000         0.357500
std     10.482877   34096.960282         0.479864
min     18.000000   15000.000000         0.000000
25%     29.750000   43000.000000         0.000000
50%     37.000000   70000.000000         0.000000
75%     46.000000   88000.000000         1.000000
max     60.000000  150000.000000         1.000000

In [7]:
from sklearn.model_selection import cross_val_score

def cv_comparison_classification(models, X, y, cv):

    cv_df = pd.DataFrame()

    for model in models:

        acc = cross_val_score(model, X, y, scoring='accuracy', cv=cv)

        acc_avg = round(acc.mean(), 3)

        cv_df[str(model)] = [ acc_avg]
        cv_df.index = ['Accuracy']

    return cv_df

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm

mlr_d = DecisionTreeClassifier(criterion = "entropy")

mlr_g = GaussianNB()

mlr_reg= LogisticRegression()

mlr_k = KNeighborsClassifier()

mlr_svc = svm.SVC(kernel='rbf')

models = [mlr_d, mlr_g, mlr_reg, mlr_k, mlr_svc]

comp_df = cv_comparison_classification(models, X, y, 5)

comp_df

,DecisionTreeClassifier(criterion='entropy'),GaussianNB(),LogisticRegression(),KNeighborsClassifier(),SVC()
Accuracy,0.807,0.888,0.82,0.882,0.9